export const DEFAULT_STATE_ARRAY = [
	{id:"1","name":"Alabama","label":"AL"},
	{id:"2","name":"Alaska","label":"AK"},
	{id:"3","name":"Arizona","label":"AZ"},
	{id:"4","name":"Arkansas","label":"AR"},
	{id:"5","name":"California","label":"CA"},
	{id:"6","name":"Colorado","label":"CO"},
	{id:"7","name":"Connecticut","label":"CT"},
	{id:"8","name":"Delaware","label":"DE"},
	{id:"9","name":"Florida","label":"FL"},
	{id:"10","name":"Georgia","label":"GA"},
	{id:"11","name":"Hawaii","label":"HI"},
	{id:"12","name":"Idaho","label":"ID"},
	{id:"13","name":"Illinois","label":"IL"},
	{id:"14","name":"Indiana","label":"IN"},
	{id:"15","name":"Iowa","label":"IA"},
	{id:"16","name":"Kansas","label":"KS"},
	{id:"17","name":"Kentucky","label":"KY"},
	{id:"18","name":"Louisiana","label":"LA"},
	{id:"19","name":"Maine","label":"ME"},
	{id:"20","name":"Maryland","label":"MD"},
	{id:"21","name":"Massachusetts","label":"MA"},
	{id:"22","name":"Michigan","label":"MI"},
	{id:"23","name":"Minnesota","label":"MN"},
	{id:"24","name":"Mississippi","label":"MS"},
	{id:"25","name":"Missouri","label":"MO"},
	{id:"26","name":"Montana","label":"MT"},
	{id:"27","name":"Nebraska","label":"NE"},
	{id:"28","name":"Nevada","label":"NV"},
	{id:"29","name":"New Hampshire","label":"NH"},
	{id:"30","name":"New Jersey","label":"NJ"},
	{id:"31","name":"New Mexico","label":"NM"},
	{id:"32","name":"New York","label":"NY"},
	{id:"33","name":"North Carolina","label":"NC"},
	{id:"34","name":"North Dakota","label":"ND"},
	{id:"35","name":"Ohio","label":"OH"},
	{id:"36","name":"Oklahoma","label":"OK"},
	{id:"37","name":"Oregon","label":"OR"},
	{id:"38","name":"Pennsylvania","label":"PA"},
	{id:"39","name":"Rhode Island","label":"RI"},
	{id:"40","name":"South Carolina","label":"SC"},
	{id:"41","name":"South Dakota","label":"SD"},
	{id:"42","name":"Tennessee","label":"TN"},
	{id:"43","name":"Texas","label":"TX"},
	{id:"44","name":"Utah","label":"UT"},
	{id:"45","name":"Vermont","label":"VT"},
	{id:"46","name":"Virginia","label":"VA"},
	{id:"47","name":"Washington","label":"WA"},
	{id:"48","name":"West Virginia","label":"WV"},
	{id:"49","name":"Wisconsin","label":"WI"},
	{id:"50","name":"Wyoming","label":"WY"}
];